/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:74: _MissingDynamic: `authors` defined outside of `pyproject.toml` is ignored.
!!

        ********************************************************************************
        The following seems to be defined outside of `pyproject.toml`:

        `authors = 'AI Developer'`

        According to the spec (see the link below), however, setuptools CANNOT
        consider this value unless `authors` is listed as `dynamic`.

        https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table

        To prevent this problem, you can list `authors` under `dynamic` or alternatively
        remove the `[project]` table from your file and rely entirely on other means of
        configuration.
        ********************************************************************************

!!
  _handle_missing_dynamic(dist, project_table)
running build_ext
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/home/runner/workspace/setup.py", line 48, in <module>
    setup(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 186, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
    dist.run_commands()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 1002, in run_commands
    self.run_command(cmd)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
    cmd_obj.run()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 99, in run
    _build_ext.run(self)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 375, in run
    self.build_extensions()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 491, in build_extensions
    self._build_extensions_serial()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 517, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/runner/workspace/setup.py", line 45, in build_extension
    subprocess.check_call(["cmake", ext.sourcedir] + cmake_args, cwd=build_temp)
  File "/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/runner/workspace', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/runner/workspace/build/lib.linux-x86_64-cpython-311/', '-DPYTHON_EXECUTABLE=/home/runner/workspace/.pythonlibs/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.